### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types named "JSON".

### ISSUE THREAD

**Issue by christoshrousis** [ng-hai/simple-trello#15]
**Describe the bug**
I'm unable to run the project from a fresh clone. I'm unsure why this is happening. When I run gatsby develop I get the error Error: Schema must contain uniquely named types but contains multiple types named "JSON".

**To Reproduce**
Install from fresh.

**Expected behavior**
Expect it at least to boot up.

**Screenshots**
![image](https://user-images.githubusercontent.com/951957/68291700-860d9c00-00de-11ea-8a72-57d13ac5fe33.png)

**Additional context**
Node 12.13.0 on nvm.
I'm not even sure where to start debugging this, I'm going to assume it has a few to many things out of date or something.

**Comment by ng-hai** [comment]
This project has not been updated since last year, you could use Node v10 instead of 12 to make it work.

**Comment by christoshrousis** [comment]
Thanks so much mate, I got it running on node 10, npm 6.13, yarn 1.7 and gatsby global 1.1.58

If I can work out a way to upgrade it I'll make a pr 😊

**Comment by ng-hai** [comment]
Sure @christoshrousis

**Comment by ng-hai** [comment]
I also have a plan to use Next.js for it instead Gatsby
